version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: eu-pescador-wiki
    expose:
      - '4002'
    ports:
      - '4002:4002'
    command: npm run dev
  db:
    container_name: "postgresDbWiki"
    image: "postgres:latest"
    ports: 
      - "5433:5433"
    volumes:
      - db_persdata:/var/lib/db
    command: postgres -c port=5433
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}
