version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: proespecies-wiki
    expose:
      - '4002'
    ports:
      - '4002:4002'
    command: npm run dev
  db:
    container_name: "postgresDbWiki"
    image: "postgres:latest"
    ports: 
      - "5433:5434"
    volumes:
      - db_persdata:/var/lib/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}
